# 项目相关配置
ruoyi:
  # 名称
  name: EndlessManager
  # 版本
  version: 2.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /www/minecraft_manager/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 白名单页面网站地址
app-url:

baidu:
  # 百度IP定位API KEY
  # 申请地址：https://lbsyun.baidu.com/index.php?title=webapi/ip-api
  # 默认key极不稳定，申请后请将key替换为你自己的key！
  key: 1ilMd2g27l7TgJwRZubialb5Bb4H6DZT

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 10

# 日志配置
logging:
  level:
    cc.endmc: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 允许循环依赖
  main:
    allow-circular-references: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  jackson:
    time-zone: Asia/Shanghai
  # 解决springfox-boot-starter在Spring Boot 2.7.x中的兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cc.endmc.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 邮件服务配置
email:
  # 是否启用邮件服务
  enable: true
  # 邮件服务提供商类型：aliyun, qq, 163, gmail, outlook等
  type: aliyun
  # 发件人邮箱账号
  account: support@mcpeach.cc
  # 发件人邮箱密码或授权码
  password: 85G9BUobquaJ6nNt
  # 发件人显示名称
  senderName: "Minecraft Server"
  # 自定义SMTP服务器配置（可选）
  # smtpHost: smtp.example.com
  # smtpPort: 465
  # ssl: true

whitelist:
  easyauth: true
  # ip限流
  iplimit: 3
  # 管理员通知邮箱
  email:

# 加密配置
encrypt:
  # 加密密钥 使用 openssl rand -base64 16 命令生成
  # 严格保管，不可泄露！
  key: o85Ultxa3spqSVd3RcUP1w==

# RCON配置 如果你不清楚这些是干什么的请勿修改！
rcon:
  # 超时时间
  timeout: 5000
  # 重连延迟时间
  reconnect-delay-ms: 1000
  # 最大响应大小 请勿盲目修改！
  max-response-size: 4096
  # 最大缓冲区大小 请勿盲目修改！
  max-buffer-size: 8196

# QQ机器人配置
qq:
  bot:
    # 重连间隔时间（单位：秒）
    reconnect-interval: 30
    # 重置时间（单位：秒）（超过该时间未重连则重置重连次数）
    reset-time: 600
    # 重连最大次数
    max-reconnect-attempts: 10